title: Portafolio de Proyectos - [Luis Gerardo Souberbielle Murillo]
description: Aqui se adjuntan los trabajos hechos a lo largo del semestre en la materia de programación numérica.
url: "https://gerardosouberbielle.github.io/Proyecto-programacion-/"
repository: [gerardosouberbielle]/[proyecto-programacion-]

theme: minimal # Puedes probar 'architect', 'cayman', 'dinky' si quieres ver otros.

collections:
  categorias:
    output: true
    permalink: /categorias/:name/

author: Gerardo Souberbielle
email: A371987@alumnos.uaslp.mx
